language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - MAKEPOT="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="sale_quotation_sourcing,sale_sourced_by_line,sale_quotation_sourcing_stock_route_transit,sale_sourced_by_line_sale_transport_multi_address,sale_properties_dynamic_fields,sale_line_quantity_properties_based,sale_line_price_properties_based" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="sale_quotation_sourcing,sale_sourced_by_line,sale_quotation_sourcing_stock_route_transit,sale_sourced_by_line_sale_transport_multi_address,sale_properties_dynamic_fields,sale_line_quantity_properties_based,sale_line_price_properties_based" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_sourced_by_line" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_sourced_by_line" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_quotation_sourcing" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_quotation_sourcing" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_quotation_sourcing_stock_route_transit" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_quotation_sourcing_stock_route_transit" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_sourced_by_line_sale_transport_multi_address" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_sourced_by_line_sale_transport_multi_address" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_properties_dynamic_fields" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_properties_dynamic_fields" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_line_quantity_properties_based" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_line_quantity_properties_based" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_line_price_properties_based" LINT_CHECK="0"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_line_price_properties_based" LINT_CHECK="0"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
