# -*- coding: utf-8 -*-
{
    'name': "Accounting Autolamps",
    'summary': """
        Contains Specific customizations for Autolamps Accounting-Related modules
        """,
    'author': "Tritel Technologies Ltd",
    'website': "http://www.tritel.co.ke",
    'version': '8.0.1.0.0',
    'category': 'Accounting & Finance',
    'license': 'AGPL-3',
    'depends': [
            'account_voucher',
            'account_followup',
            'point_of_sale',
            'pos_autolamps',
            'report_xlsx',
        ],
    'data': [
        'report/report_invoice.xml',
        'report/payment_receipt.xml',
        'report/report_ledger_summary.xml',
        'data/email_template.xml',
        'views/accounting_voucher.xml',
        'views/res_partner.xml',
        'views/res_currency.xml',
        'views/account_invoice.xml',
        'views/account_payment_term.xml',
        'views/sale_order.xml',
        'report/due_payments.xml',
        'automation/schedulers.xml',
        'views/post_dated_cheque.xml',
        'views/accounting_followup.xml',
        'security/accounting_autolamps_security.xml',
        'security/ir.model.access.csv',
        'report/vat.xml',
        'views/account.xml',
        'data/account.tax.code.csv',
        'data/account.tax.csv',
        'views/res_config_view.xml',
        'views/pos_order.xml',
        'wizard/partner_ledger_summary.xml',
        ],
}
