# -*- coding: utf-8 -*-
{
    'name': "Autolamps Project Depencencies Module",
    'summary': """
        Autolamps Base Module containing all dependencies
        """,
    'author': "Tritel Technologies Ltd",
    'website': "http://www.tritel.co.ke",
    'version': '8.0.1.0.0',
    'license': 'AGPL-3',
    'depends': [
            'account_accountant',
            'account_voucher',
            'accounting_autolamps',
            'auth_admin_passkey',
            'approvals_customer_credit_limit',
            'aspl_pos_sales_commission',
            'autolamps_base',
            'base_name_search_improved',
            'base_search_fuzzy',
            'calendar',
            'l10n_ke',
            'mail',
            'payment_mpesa',
            'point_of_sale',
            'pos_autolamps',
            'pos_disable_payment',
            # 'pos_order_load',
            'pos_extra_utilities',
            'pos_order_summary',
            # 'pos_warehouse_management',
            'aspl_pos_sales_commission',
            'pos_restrict_price_change',
            'product_autolamps',
            'pos_printing_autolamps',
            'purchase',
            'purchase_order_autolamps',
            'sale',
            'sale_automatic_workflow',
            'sale_commission',
            'sale_commission_formula',
            'sale_order_autolamps',
            'sale_sourced_by_line',
            'sms_gateway',
            'stock',
            'stock_autolamps',
            'stock_available_unreserved',
            'stock_inventory_chatter',
            'stock_no_negative',
            'stock_traceability_operation',
            'website',
            'website_sale',
            'website_backend_auto_operation',
            'web_site_sale_extend',
            'website_sale_default_country',
            'website_sale_recently_viewed_products',
            'website_sale_checkout_comment',
            'website_sale_require_login',
            'website_product_share',
            'website_sale_cart_preview',
            # 'website_sale_category_megamenu',
        ],
    'data': [
        
        ],
}
